(setq ffap-bindings nil)
(setq make-backup-files nil)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(setq ring-bell-function 'ignore)
(global-display-line-numbers-mode 1)
(setq auto-window-vscroll nil)
(fset 'yes-or-no-p 'y-or-n-p)
(delete-selection-mode 1)
(electric-pair-mode 1)
(global-subword-mode 1)
(setq-default indent-tabs-mode nil
              tab-width 2)
(setq require-final-newline t)
(add-hook 'before-save-hook #'delete-trailing-whitespace)
(setq-default cursor-type 'bar)
(blink-cursor-mode 0)
(setq org-edit-src-content-indentation 0)
(setq org-src-preserve-indentation t)
(beacon-mode 1)
