;; Settings
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)
(setq initial-scratch-message nil)

;; Splash Setup
(defvar apps-buffer nil "Application Menu")
(defun application-buffer ()
  (setq apps-buffer (get-buffer-create "*apps*"))
  (with-current-buffer apps-buffer
    (let ((inhibit-read-only t))
      (erase-buffer)
      (let* ((window-width (window-width))
             (window-height (window-height))
             (vertical-offset (/ window-height 6)))
        (insert (make-string vertical-offset ?\n))
        (when (display-graphic-p)
          (let ((image (create-image (or (getenv "NIXMACS_LOGO_PATH") "/nix/store/kpyllsr5w4618ga2js1yykg47nb0pjpm-nix_emacs_logo_small.png") nil nil :ascent 'center)))
            (when image
              (let* ((image-width (round (car (image-size image))))
                     (padding (make-string (max 0 (/ (- window-width image-width) 2)) ?\ )))
                (insert padding)
                (insert-image image)
                (insert "\n\n")))))
        (let* ((text " Applications  \n")
               (text-width (length text))
               (padding (make-string (max 0 (/ (- window-width text-width) 2)) ?\ )))
          (insert padding text "\n"))
        (let* ((lists '(("m" "EMMS")
                        ("i" "i3 configuration file")
                        ("e" "emacs configuration file")
                        ("n" "nixos configuration file")
                        ("x" "xmonad configuration file")
                        ("p" "polybar configuration file")
                        ("h" "home-manager configuration file")
			  ("q" "quit emacs"))))
	  (dolist (item lists)
            (let* ((key (car item))
                   (desc (cadr item))
                   (line (format "%s => %s" key desc))
                   (padding (make-string (max 0 (/ (- window-width (length line)) 2)) ?\ )))
              (insert padding line "\n"))))
        (insert "\n\n")
        (let* ((instruction "Press b to go back...")
               (instruction-width (length instruction))
               (padding (make-string (max 0 (/ (- window-width instruction-width) 2)) ?\ )))
          (insert padding instruction))))
    (setq buffer-read-only t)
    (goto-char (point-min))
    ;; Setup keybindings inside the buffer context
    (local-set-key (kbd "b") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (switch-to-buffer "*splash*")))
    (local-set-key (kbd "m") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (call-interactively 'emms-browser)))
    (local-set-key (kbd "i") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (find-file "~/.config/i3/config")))
    (local-set-key (kbd "x") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (find-file "~/.xmonad/xmonad.hs")))
    (local-set-key (kbd "e") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (find-file "~/.e.org")))
    (local-set-key (kbd "p") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (find-file "~/.config/polybar/config.ini")))
    (local-set-key (kbd "n") (lambda ()
			       (interactive)
			       (kill-buffer "*apps*")
			       (find-file "/sudo::/etc/nixos/configuration.nix")))
    (local-set-key (kbd "f") (lambda ()
			       (interactive)
			       (kill-buffer "*apps*")
			       (find-file "/sudo::/etc/nixos/flake.nix")))
    (local-set-key (kbd "h") (lambda ()
			       (interactive)
			       (kill-buffer "*apps*")
			       (find-file "/sudo::/etc/nixos/home.nix")))
    (local-set-key (kbd "q") (lambda () (interactive)
			       (kill-buffer "*apps*")
			       (call-interactively 'save-buffers-kill-terminal))))
  ;; Switch to the apps-buffer
  (switch-to-buffer apps-buffer))

(defun my-custom-splash-screen ()
  "Display custom splash screen with centered logo and text."
  (let ((splash-buffer (get-buffer-create "*splash*")))
    (with-current-buffer splash-buffer
      (erase-buffer)
      (let ((inhibit-read-only t))
        ;; Calculate center position for window
        (let* ((window-width (window-width))
               (window-height (window-height))
               ;; Insert some vertical spacing to center content
               (vertical-offset (/ window-height 6)))
          ;; Add vertical spacing
          (insert (make-string vertical-offset ?\n))
          ;; Insert and center the image
          (when (display-graphic-p)
            (let ((image (create-image (or (getenv "NIXMACS_LOGO_PATH") "/nix/store/kpyllsr5w4618ga2js1yykg47nb0pjpm-nix_emacs_logo_small.png") nil nil :ascent 'center)))
              (when image
                (let* ((image-width (round (car (image-size image))))  ; Convert to integer
                       (padding (make-string (max 0 (/ (- window-width image-width) 2)) ?\ )))
                  (insert padding)
                  (insert-image image)
                  (insert "\n\n")))))
          ;; Insert centered text
	  (let* ((text " Welcome to NixMacs!  \n")
		 (text-width (length text))
		 (padding (make-string (max 0 (/ (- window-width text-width) 2)) ?\ )))
	    (insert padding text "\n"))
          (let* ((text "C-x C-f => Open or Create File")
                 (text-width (length text))
                 (padding (make-string (max 0 (/ (- window-width text-width) 2)) ?\ )))
            (insert padding text "\n"))
	  (let* ((text "C-x d => Navigate to Directory")
		 (text-width (length text))
		 (padding (make-string (max 0 (/ (- window-width text-width) 2)) ?\ )))
	    (insert padding text "\n"))
	  (let* ((text "a => Show Application Menu")
		 (text-width (length text))
		 (padding (make-string (max 0 (/ (- window-width text-width) 2)) ?\ )))
	    (insert padding text "\n"))
	  (let* ((text "q => Quit Emacs")
		 (text-width (length text))
		 (padding (make-string (max 0 (/ (- window-width text-width) 2)) ?\ )))
	    (insert padding text "\n"))
          ;; Add some more spacing
          (insert "\n\n")
          (let* ((instruction "Press key to continue...")
                 (instruction-width (length instruction))
                 (padding (make-string (max 0 (/ (- window-width instruction-width) 2)) ?\ )))
            (insert padding instruction))))
      ;; Make buffer read-only
      (setq buffer-read-only t)
      (goto-char (point-min)))
    ;; Display the buffer
    (switch-to-buffer splash-buffer)
    ;; Set up key bindings
    ;; Try multiple ways to bind the Enter/Return key
    (local-set-key (kbd "RET") (lambda () (interactive)
                                 (kill-buffer "*splash*")))
    (local-set-key (kbd "<return>") (lambda () (interactive)
                                      (kill-buffer "*splash*")))
    (local-set-key [return] (lambda () (interactive)
                              (kill-buffer "*splash*")))
    (local-set-key [13] (lambda () (interactive)
                          (kill-buffer "*splash*")))
    (local-set-key (kbd "f") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "/sudo::/etc/nixos/flake.nix")))
    (local-set-key (kbd "i") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "~/.config/i3/config")))
    (local-set-key (kbd "x") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "~/.xmonad/xmonad.hs")))
    (local-set-key (kbd "p") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "~/.config/polybar/config.ini")))
    (local-set-key (kbd "m") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (call-interactively 'emms-browser)))
    (local-set-key (kbd "n") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "/sudo::/etc/nixos/configuration.nix")))
    (local-set-key (kbd "h") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "/sudo::/etc/nixos/home.nix")))
    (local-set-key (kbd "a") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (application-buffer)))
    (local-set-key (kbd "e") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "~/.e.org")))
    (local-set-key (kbd "t") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (find-file "~/Documents/temp.org")))
    (local-set-key (kbd "q") (lambda ()
			       (interactive)
			       (kill-buffer "*splash*")
			       (call-interactively 'save-buffers-kill-terminal)))))


;; Conditional Loading
(defun my/maybe-show-splash ()
  (interactive)
  (when (and (display-graphic-p)
             ;; Show splash when current buffer is a scratch/internal buffer
             ;; (not a user file being opened at startup)
             (string-prefix-p "*" (buffer-name))
             (= (length (window-list)) 1))
    (my-custom-splash-screen)))

;; Hook
(add-hook 'window-setup-hook #'my/maybe-show-splash)
